name: Build and Push Docker Image (Build with Dockerfile)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile # 위에서 작성한 Dockerfile 사용
          push: true
          tags: ${{ secrets.REGISTRY_SERVER }}/v2:${{ github.sha }}
          labels: |
            org.opencontainers.image.source: ${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision: ${{ github.sha }}
            org.opencontainers.image.created: ${{ github.event.inputs.timestamp }}

      - name: Image digest
        if: ${{ steps.build-push.outputs.digest }}
        run: echo "Image digest:${{ steps.build-push.outputs.digest }}"
